### PR TITLE
docs: add code-quality-resources

### PR DESCRIPTION
**Pull request by developer239**
Collection of multiple code quality resources:

- eslint-config-react-native
- eslint-config-typescript
- eslint-config-react
- eslint-config-node
- eslint-config-jest
- eslint-config-functional

### CODE REVIEW

**Comment by dustinspecker** [comment]
Thank you for the pull request!

I'm not understanding how these differ from other popular solutions such as https://github.com/prettier/eslint-config-prettier. Also, projects like https://github.com/yannickcr/eslint-plugin-react provide a recommended configuartion.

**Comment by developer239** [comment]
@dustinspecker Personally, I believe that popular standard configurations are not strict enough. Give my config a try and you will see a difference. 🙂👌 Also, I would appreciate the feedback. The reason my configuration is so strict is that I believe that linters can force us to be better programmers.

**Comment by developer239** [comment]
@dustinspecker I just added 🙂 

- ramda configuration
- graphql configuration
- angular configuration

**Comment by dustinspecker** [comment]
Hey. Can you rebase this please? Happy to accept afterwards.

**Comment by developer239** [comment]
@dustinspecker sure 🙂 I will probably create new PR though because I migrated my linters to monorepo.

**Comment by dustinspecker** [comment]
I'm going to close this, but please feel free to reopen if you'd like to. Happy to accept another PR instead as well.

**Pull request closed without merging**
