### PR TITLE
Add eslint-plugin-json-schema-validator

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR adds [eslint-plugin-json-schema-validator](https://github.com/ota-meshi/eslint-plugin-json-schema-validator).

### CODE REVIEW

**Comment by brettz9** [comment]
Although I know this may validate data which gets consumed as a normal part of one's JavaScript application and enforcing best practices there, I would think that this might fall more under our specific "Languages" section?

**Comment by ota-meshi** [comment]
Since eslint-plugin-json-schema-validator can also be verified with [JavaScript], [JSON] and [YAML], I found it difficult to categorize it as "Languages". Do you think it's better to specifically categorize it as "JSON"?

[JavaScript]: https://ota-meshi.github.io/eslint-plugin-json-schema-validator/playground/#eJxVjU1uhDAMha9ieYmASNWsIvUI7QXGLFIwhRE4M07mR0LcfZLCqK2Tjd/7/N6C/Tjxp5sZLdYcplGitvUpYImt77JqCth0OAUvVWgHnl11c9PYuejViK9G+VktHFnVawnLRgV7hCUXfLjYDsmmPx0FYVNunCUcYjwHa0zuqPfrlM6112/zuiFcoVkbKAwJyey768Q1P85eY4B3WEggDT8iSxdSHRzeoCl3VW72ReT5Un8PrBaiXnmT1x3VFBv+wXzJzwLh3akQlr9WiDq2MVu+7wn3JJL0cX0CMONyqw==
[JSON]: https://ota-meshi.github.io/eslint-plugin-json-schema-validator/playground/#eJxljUFuwzAMBL9C8GjYFlDkpD/0BaEPjkzXKlyqpZSkgOG/R6rcoEApXrizu9rQhYnRommA4+olwXsM0kW38MfY3cbVT2MKaiR0Xn5OC2dWDdrCVl3RnmGb/cqvY3JLxoR97VLXN4RDW32WcEnpM1pjyh/9kc7t3Ad9M78Zwh2GfYDGkGwkkIeQvxPLFAlzP5xeYGifRG5FPZxVu2i4R9aiJ71yRfszoteV478Qf5VXZML7qELY/sUxqXep4jDPhEcrSV7cH13aaNc=
[YAML]: https://ota-meshi.github.io/eslint-plugin-json-schema-validator/playground/#eJxNjU1OxDAMRq9imR3qj4RY5Q5wgXEXIXVpUJqAnZkBVb07yQQQ8srvffa34+IDP9uN0eDAGnzM4oYvuwXs0KW58jtoAt40xV7dypvtLzb42eYkY0y9j7fVwIlFknSwt5SaE+y14clmtxZN/0ruCaeu5QzhmvO7mnGsHcPPdfnOQ5LX8feG8IDpmCiWQf7MHGclLH/h8QGmG4yXAigCEL5IuipLDWQ5c9VyDqx/Af6oUz3h1UrxjWsW73LjaVkqxuMbT0pm4A==

**Comment by brettz9** [comment]
Yes, understood, and I can see why you consider it as such a tool since that is its actual function, but to me, I'd be concerned that those working with JSON (or YAML) would be more likely to miss out on your very promising tool because they would be looking through "Languages" to find support for JSON Schema (and would be the users most likely to want to discover JSON Schema capabilities). Even those seeking to work with JavaScript objects in such a way would still probably think to look to Languages to find tools for enforcing JSON schema on their data structures.

(FWIW, I'd say the same thing if I were to turn my `jsdoc-sonschema` project into a linting tool; even if it could process jsdoc within JavaScript and then use that to validate JavaScript as well as JSON objects, if forced to choose a single audience, I think "Languages" would be it.)

So while I understand your project is not merely for handling some external data types, my thinking is that its home that would find the most likely interested users would be under Languages, especially with awesome list projects such as `awesome-eslint` not aiming for such a degree of precision of allowing multiple entries or projects listed within sortable tables and such.

But if you remain unconvinced, I don't think it's wrong where you have it, and indeed some looking through Practices might become interested to explore it further.

**Comment by ota-meshi** [comment]
Thank you for your comment!
I moved it to the `"Languages"."JSON"` section.

**Pull request merged**
