### PR TITLE
Add tutorials section with articles and videos

### PR DESCRIPTION
**Pull request by trevordmiller**

### CODE REVIEW

**Comment by gajus** [comment]
While not explicitly stated in the [`./contributing.md`](https://github.com/dustinspecker/awesome-eslint/blob/8ed6394d6b4555ad53f5858965c501d397597c00/contributing.md) guidelines, it is apparent that author intends to follow alphabetical order for content. Therefore, please add Tutorials section after Tools.

**Comment by trevordmiller** [comment]
@gajus ✅

**Comment by gajus** [comment]
@trevordmiller Thank you.

LGTM

**Comment by dustinspecker** [comment]
Great idea! Thank you!

**Pull request merged**
