### PR TITLE
Add eslint-config-es as very strict rules set.

### PR DESCRIPTION
**Pull request by goloroden**

### CODE REVIEW

**Comment by dustinspecker** [comment]
I am really sorry for not seeing this sooner. Not sure how I missed it.

Would you be able to add to its readme briefing users why they should use it? It's not immediately obvious (to me at least) how it's stricter or how it benefits users.

Thank you and really sorry again for missing this.

**Comment by goloroden** [comment]
Thanks for getting back to me (and no problem that it took a while).

I like your suggestion and added a hint on this to the project's `README.md`. See [this part of it](https://github.com/thenativeweb/eslint-config-es#quick-start) for details:

> This module contains a very strict ESLint configuration for ES2015 and above, both for server and client development. Its aims to eradicate any variation in code style. If you can not tell any more, based on little individual manners, who of your co-workers wrote a piece of code, this module succeeded. This helps you to narrow down your focus to pure functionality, as you do not have to think about code styling any more at all.

Better ;-)?

**Comment by sadorlovsky** [comment]
@dustinspecker I'm sorry, despite the fact that I can accept PR's I though hesitate a bit to do it without your decision as owner :grin:

**Comment by dustinspecker** [comment]
@goloroden Thanks!

@sadorlovsky No worries. I trust your judgement. It's easy enough to discuss and revert PRs if one of us believes a PR should not have been accepted.

**Pull request merged**
