### PR TITLE
Add eslint-plugin-this

### PR DESCRIPTION
**Pull request by matijs**
Add https://github.com/matijs/eslint-plugin-this an ESLint plugin that disallows the use of `this`

### CODE REVIEW

**Comment by adriantoine** [comment]
This is already in both [eslint-plugin-fp](https://github.com/jfmengels/eslint-plugin-fp/blob/master/docs/rules/no-this.md) and [eslint-plugin-immutable](https://github.com/jhusain/eslint-plugin-immutable#no-this) 😛

**Comment by matijs** [comment]
Ah, indeed it is. No harm though in adding it when all you're looking for is to prevent the use of `this` I assume.

**Comment by jfmengels** [comment]
@adriantoine ah, thanks for noticing, will update that later :p.
FYI there is also eslint-plugin-better that has this same rule.

**Comment by dustinspecker** [comment]
I'm cool adding this for now. I could see people wanting to avoid `this` without concern for fp or immutable. We can always re-evaluate in the future if we get a lot of one-off rule plugins.

Thank you!

**Pull request merged**
