### PR TITLE
- Performance plugins

### PR DESCRIPTION
**Pull request by brettz9**
Added two performance-related linting plugins

### CODE REVIEW

**Comment by dustinspecker** [comment]
Ooo, these are cool. Do you mind fixing linting issues? Happy to merge these afterwards.

**Comment by brettz9** [comment]
Ah, apologies--Amended. I also added a commit if you're ok with it--to have an `.editorconfig`, especially helpful in such cases when there is no `.eslintrc.*` file to get the enforced code (though I know I should have checked that).

**Comment by dustinspecker** [comment]
Thank you! That's a great addition - good catch.

**Comment by brettz9** [comment]
Cool--and thanks for the repo access. A very useful collection to have all in one place!

**Pull request merged**
