### PR TITLE
adds eslint-plugin-woke to plugins list

### PR DESCRIPTION
**Pull request by amwmedia**

### CODE REVIEW

**Comment by developer239** [comment]
@amwmedia so did you just accidentally create a dictionary of profanity? Look at the source code. This is the craziest thing I have seen on GitHub.

**Comment by brettz9** [comment]
Although I'm not sure how big of a problem it is with people using offensive terms within their call expressions and code comments, I can see that whether for moral reasons and/or reasons of legal protection, people might wish to make use of such a tool. Of course, as a JavaScript linting tool, it also wouldn't catch offensive expressions used in plain text or non-JS portions of Markdown files and such, so it wouldn't be fail-safe.

I'm personally a bit ambivalent about policing language if presented as though this will address the root of deeper problems, but I personally see no problem with people having the opportunity to be informed about such a tool and use it to ensure their project catches any clear violations of the standards they want to follow. One surely needs to collect the offensive words in order to be able to find them (unless expecting this to be an AI tool), so I don't see that as an issue either.

Note there currently may be some false positives, e.g., `invert`: https://github.com/amwmedia/eslint-plugin-woke/blob/master/lib/categories/LGBTQ.js#L16 . Just a thought, @amwmedia , that you might want to allow a whitelist out of these terms or a supplementary blacklist.

FWIW, while I think it is fortunate you indicate in source that certain words like "blacklist" merely "*could be* seen as offensive" rather than asserting they definitely are, as a former applied linguistics major, I find some of these objections in the community (such as ESLint itself has attempted to follow with itself removing `blacklist`) to be an overreach and even counterproductive to the cause of addressing real racism. Many of these terms are no more problematic in their etymology than "whitewash" is (even "black-hearted" suggests "black" as in the darkness that all cultures have non-arbitrary reasons to fear). To me such changes are going way too far, but that's just me (I'd also be willing to bet the likes of the distinguished linguist, John McWhorter (who is African-American) would be annoyed by this also). But again, a whitelist could at least let words like this be optional. The `master`->`main` change as GitHub made is at least arguable (even if the word is not being used literally--e.g., like "crusade" can be).

@dustinspecker , you have any objections to adding this tool?

**Comment by dustinspecker** [comment]
I'm cool with adding this. I personally like tools like this because there are legit some words/phrases I'm not aware of as potentially being offensive to others.  Is there room for improvement? Sure. I think this is a hard problem because so much of it needs to be context-aware.

@amwmedia Have you seen https://github.com/get-alex/alex? You might consider reaching out to them and seeing if there's some way to combine efforts.

I've pushed a commit that fixes lint issues that were failing CI on this pull request, so all good on that.

**Comment by amwmedia** [comment]
@developer239 Yeah, in order to help others avoid offensive words... this codebase ends up becoming a cesspool 😆

**Comment by amwmedia** [comment]
@brettz9 This codebase is still pretty young and I'm sure there are many ways it could be improved. I'm also sure that there are many more lists to come in the future. 😉

**Comment by amwmedia** [comment]
Also... @brettz9 I very much enjoy the irony of your suggestion that we add a "blacklist" and "whitelist" 😂

**Comment by brettz9** [comment]
The choice was deliberate. In my view, it is only actually ironic if we take our language to extremes and see offense in words that are not and have not been actually denigrating to a person who understands the science of language. If I had prefaced my suggestions by calling you "My honkey", then I'd agree, that'd be ironic... :-)

**Comment by developer239** [comment]
Maybe it is just me but I don't think I need tools like this in our team. **If your developers commit racist vulgarities then you have a problem that not eslint plugin can solve.**

Calling - probably the most offensive - repository on GitHub `woke` seems like a bad joke. 👌 

@amwmedia @brettz9 @dustinspecker

**Comment by brettz9** [comment]
> **If your developers are racist or commit vulgarities/profanities then you have a problem that not eslint plugin can solve.**

It is possible that one accepts PRs, or has code one doesn't know is offensive, or that in an earlier phase of a project, the project or some open source code added to the project may have just had some crassness with some curse words, e.g., criticizing some difficult-to-use software or something. I've seen that in projects I've worked with and the person was not a troll or anything. But again, there is the "trust but verify" principle–it doesn't hurt to check.
 
> Calling - probably the most offensive - repository on GitHub `woke` seems like a bad joke. 👌

How do you think sites like Yahoo have profanity filters? They need code to detect problems in the first place. This is open source, so naturally the code is going to be available for introspection. And that is a good thing–one wouldn't want to be omitting words or adding inoffensive words.

Besides, this is not exposing people to words that aren't available elsewhere, nor are they on its main public-facing page, the README, giving prominence to the words themselves.

This seems like an impractically purist argument. Besides, words are not like magic incantations–they don't offend just by themselves. There are slang dictionaries for example which help people understand their meaning, whether to avoid them, or to respond to people using them. It is necessary to also look to intent, context, and prominence with these kinds of things, and not thing of these things in a superstitious kind of vein.

**Pull request merged**
