### PR TITLE
Add Diff

### PR DESCRIPTION
**Pull request by paleite**

### CODE REVIEW

**Comment by brettz9** [comment]
Hi,

Interesting... Does this have use cases for linting staged only distinct from say:

```json
{
  "scripts": {
    "lint-arg": "eslint --cache",
  },
  "lint-staged": {
    "*.js": "npm run eslint-arg --"
  }
}
```

...given that `lint-staged` supplies the staged file name as an argument which can be passed to eslint to ensure it doesn't lint everything?

Is the primary use here being for non-staged as well as staged changes?

**Comment by paleite** [comment]
Yes! 😃 

It can be used to lint only staged changes in  a pre-commit hook with something like lint-staged (my original use-case, which got me to write it), and it can be used to diff between commits and commit ranges.

It also supports passing commits and commit ranges as an environment variable, which makes it useful in CI environments, too.

**Comment by paleite** [comment]
It matches on all files (regardless of extension) and it honors .eslintignore

In essence it’s completely transparent in the error-reporting and all it does is removes/filters errors that are reported outside of the staged range.

**Comment by brettz9** [comment]
Ok, sure, but I'm wondering if there are any advantages over just using `lint-staged` if a person is only interested in linting staged changes? Because one can, as per my example, use `lint-staged` without any additional plugins to do that, since lint-staged passes the file name to the script and eslint can be run against just the changed file(s).

**Comment by paleite** [comment]
Ah, thanks for asking me to clarify! This plugin only lints the changes in each staged file, rather than the full staged file.

Example:
- you fix a typo on line 3 in file a.js
- Your ESLint setup identifies an issue on line 548 in file a.js (completely unrelated to your typo)

traditionally, you’d have to fix that error or commit with --no-verify. But with this plugin, only your change would be linted.

Effectively it allows you to ensure your submitted code is linted, without being forced to fix every issue in a file you touched.

lint-staged passes every changed file, and this plugin additionally filters out errors you didn’t create in those files.

This is especially handy when introducing new linter rules in a large team or when ensuring a PR’s changes are up to par.

let me know what you think! 🙂

**Comment by paleite** [comment]
Come to think of it: There’s a similar tool for Prettier
https://www.npmjs.com/package/precise-commits

**Comment by brettz9** [comment]
> Ah, thanks for asking me to clarify! This plugin only lints the changes in each staged file, rather than the full staged file.

Ah, I see... A very good way to get new projects into linting. Seems a nice fit with https://github.com/IanVS/eslint-nibble , even while the projects offer different things.

> Effectively it allows you to ensure your submitted code is linted, without being forced to fix every issue in a file you touched.

Great.

> lint-staged passes every changed file, and this plugin additionally filters out errors you didn’t create in those files.
> 
> This is especially handy when introducing new linter rules in a large team or when ensuring a PR’s changes are up to par.
> 
> let me know what you think! 🙂

Sounds great.

Btw, I hope @dustinspecker doesn't mind me inquiring a bit into the rationale of the plugins. I wasn't pushing back on inclusion even originally, but just wanting to understand the extent to which it is an "awesome" tool, and it looks like it is. :-)

The one thing I might suggest in this PR is clarifying your plugin's specialty by changing "Run ESLint on your changes only" to "Run ESLint on your changed lines only" to distinguish this from what might be interpreted as "changed files only".

**Comment by paleite** [comment]
> The one thing I might suggest in this PR is clarifying your plugin's specialty by changing "Run ESLint on your changes only" to "Run ESLint on your changed lines only" to distinguish this from what might be interpreted as "changed files only".

That’s great feedback! I’ve amended the PR accordingly. Thanks for your help and the kind words.

**Comment by brettz9** [comment]
Sure! Thanks for providing this to the community and sharing with us... You might also see #161 for a suggestion on where else you (or others here) might share.

**Comment by dustinspecker** [comment]
I appreciate this discussion a bunch. The clarification and support of linting only changed lines instead of changed files is awesome. This is super cool. Thank you!

**Pull request merged**
